site_name: Métodos de resolución de ODEs

theme:
    name: "material"

plugins:
    - mkdocstrings

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
    - Introducción: index.md
    - Documentación: reference.md
